server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost/ego?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    password: root@123
    username: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  application:
    name: item-service  #应用名称
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  configuration:
    log-impl:
      org.apache.ibatis.logging.stdout.StdOutImpl